# Generated by Django 5.1 on 2024-11-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0010_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
