# Generated by Django 5.1 on 2024-11-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0011_profile_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pinterest_url',
        ),
    ]
