# Generated by Django 5.1 on 2024-11-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0012_remove_profile_pinterest_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
    ]
