# Generated by Django 5.1 on 2024-11-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_author',
            new_name='post',
        ),
    ]
